name: schooltech
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  custom_signin_buttons: ^1.0.2
  flutter_svg: ^1.1.6
  http: ^0.13.5
  shared_preferences: ^2.0.15
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/avatar_male.png
   - assets/images/background_login.jpg